export const HowItWorksData = [
  {
    title: 'Big Data Engineering',
    des: 'At the core of our solution lies the power of big data engineering. It handles the vast amounts of data generated by educational institutes, including videos, documents, and learner interactions. Through robust data processing pipelines and scalable storage systems, big data engineering ensures the efficient management and utilization of educational data.',
  },
  {
    title: 'Auto ETL (Extract, Transform, Load) Scenarios',
    des: 'The Auto ETL component automates the extraction, transformation, and loading of data from diverse sources, ensuring data compatibility and integrity. It handles the complexity of data integration, aggregation, and standardization, enabling seamless integration of diverse educational resources into a unified platform.',
  },
  {
    title: 'LLM (Large Language Models)',
    des: 'Large Language Models, such as the one powering our solution, leverage the latest advancements in natural language processing and machine learning. These models are trained on vast corpora of text data, enabling them to understand and generate human-like text. LLMs form the foundation of our AI-powered summarization, question- generation, and chatbot capabilities.',
  },
  {
    title: 'Cognitive Data Science',
    des: 'Our solution utilizes cognitive data science techniques to analyze and evaluate the quality of educational content. By applying advanced algorithms and machine learning models, we can detect patterns, structures, and semantic information within videos and PDFs. This enables us to assess the relevance, accuracy, and educational value of the content, ensuring that learners have access to high-quality resources.',
  },
  {
    title: 'Generative AI',
    des: "The pinnacle of our product's backend infrastructure is generative AI. By harnessing the power of generative models, we enable dynamic interactions with digital content. These models analyze, interpret, and generate responses based on learner inputs, creating a natural language-based learning environment. Generative AI drives our AI summarization, Q&A practice widget, and chatbot functionalities, enabling seamless interaction with educational videos and resources.",
  },
  {
    title: 'Advanced Prompt Engineering',
    des: "Our solution utilizes advanced prompt engineering techniques to enhance the interaction between learners and generative AI models. By carefully crafting prompts, we optimize the model's responses to ensure they are contextually relevant, accurate, and aligned with the specific learning goals. This enables a more effective and productive engagement between learners and the AI system.",
  },
];
